# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdHQRSMGiM98a06Vhy6OedrEeTgmUiAa
"""

!pip uninstall -y click gtts typer wandb google-adk -q

!pip install -q click==8.1.8
!pip install -q gtts
!pip install -q openai-whisper
!pip install -q transformers
!pip install -q torch
!pip install -q ffmpeg-python

import whisper
from transformers import pipeline
from gtts import gTTS
from google.colab import files
from IPython.display import Audio

print("Upload audio file")
uploaded = files.upload()

audio_file = list(uploaded.keys())[0]

whisper_model = whisper.load_model("base")

result = whisper_model.transcribe(audio_file)
text = result["text"]

print("Transcribed Text:")
print(text)

classifier = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

prediction = classifier(text)

label = prediction[0]["label"]
score = prediction[0]["score"]

print("Sentiment:", label)
print("Confidence:", score)

if label == "POSITIVE":
    response = "Thank you for your positive feedback. We are happy."
else:
    response = "Sorry for your experience. We will improve."

print(response)

tts = gTTS(response)
tts.save("output.mp3")

Audio("output.mp3")